import Navbar from '@/component/Navbar/Navbar'
import './globals.css'
import { Kanit } from 'next/font/google'
import ImgmodalProvider from '@/context/Imgmodalcontext'
const Kanits = Kanit({ subsets: ['thai'], weight:['500'],variable: '--font-kanit', })
const Kanitslight = Kanit({ subsets: ['thai'], weight:['300'],variable: '--font-kanitlight', })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${Kanits.variable} ${Kanitslight.variable}`}>
      <body >
        <ImgmodalProvider>
        <div className=' containerfuid flex flex-col items-center mx-auto'>
          <Navbar/>
        {children}
        </div>   
        </ImgmodalProvider>
        </body>
    </html>
  )
}
